version: '3.9'
services:
  hub:
    image: registry:2
    environment:
      - REGISTRY_STORAGE_DELETE_ENABLED=true
      - REGISTRY_HTTP_ADDR=0.0.0.0:1027
    ports:
      - 1027:1027
    deploy:
      replicas: 1
      labels:
        com.registry.description: 'This platform will have some native concept of “service” that can match Compose application model.'
        enspiration: github.com/scaamanho/docker-swarm-deployments/blob/master/docker-registry/docker-registry-stack.yml?ysclid=ldmvgxjz71370185113
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.registry == +
    volumes:
      - registry:/var/lib/registry
volumes:
  registry:
    external: true